### ISSUE TITLE
I had the following problem when installing this library

### ISSUE THREAD

**Issue by dubing-bit** [OpenDroneMap/OpenSfM#21]
(uav) D:\code\OpenSfM>python setup.py build
Configuring for python 3.8...
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22621.
-- Using VCPKG FindLAPACK from package 'lapack-reference'
-- A library with LAPACK API found.
-- Using VCPKG FindLAPACK from package 'lapack-reference'
-- Failed to find SuiteSparse - Did not find AMD library (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find AMD header (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find CAMD library (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find CAMD header (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find COLAMD library (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find COLAMD header (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find CCOLAMD library (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find CCOLAMD header (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find CHOLMOD library (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find CHOLMOD header (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find CXSPARSE library (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find SuiteSparseQR library (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find SUITESPARSEQR header (required SuiteSparse component).
-- Found SuiteSparse_config library: D:/code/OpenSfM/vcpkg/installed/x64-windows/lib/suitesparseconfig.lib
-- Failed to find SuiteSparse - Failed to find either: SuiteSparse_config header & library (should be present in all SuiteSparse >= v4 installs), or UFconfig header (should be present in all SuiteSparse < v4 installs).
-- Found METIS library: D:/code/OpenSfM/vcpkg/installed/x64-windows/debug/lib/metis.lib.
-- Failed to find some/all required components of SuiteSparse. (missing: AMD_FOUND CAMD_FOUND COLAMD_FOUND CCOLAMD_FOUND CHOLMOD_FOUND CXSPARSE_FOUND SUITESPARSEQR_FOUND SUITESPARSE_VERSION)
-- Using VCPKG FindLAPACK from package 'lapack-reference'
-- A library with LAPACK API found.
-- Found required Ceres dependency: Eigen version 3.4.0 in D:/code/OpenSfM/vcpkg/installed/x64-windows/share/eigen3
-- Found Ceres version: 2.1.0 installed in: D:/code/OpenSfM/vcpkg/installed with components: [LAPACK, SuiteSparse, SparseLinearAlgebraLibrary, SchurSpecializations, Multithreading]
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Found installed version of gflags: D:/code/OpenSfM/vcpkg/installed/x64-windows/share/gflags
-- Detected gflags version: 2.2.2
-- Found OpenCV: D:/code/OpenSfM/vcpkg/installed/x64-windows (found version "4.7.0")
-- Found OpenCV: D:/code/OpenSfM/vcpkg/installed/x64-windows (found version "4.7.0") found components: core imgproc calib3d imgcodecs
-- pybind11 v2.2.4
-- Configuring done (3.4s)
-- Generating done (0.3s)
-- Build files have been written to: D:/code/OpenSfM/cmake_build
Compiling extension...
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。

  foundation.vcxproj -> D:\code\OpenSfM\cmake_build\foundation\Release\foundation.lib
  bundle.vcxproj -> D:\code\OpenSfM\cmake_build\bundle\Release\bundle.lib
  geometry.vcxproj -> D:\code\OpenSfM\cmake_build\geometry\Release\geometry.lib
  pybind.cc
D:/code/OpenSfM/vcpkg/installed/x64-windows/include\glog/log_severity.h(57,1): fatal error C1189: #error:  ERROR macro
is defined. Define GLOG_NO_ABBREVIATED_SEVERITIES before including logging.h. See the document for detail. [D:\code\Ope
nSfM\cmake_build\bundle\pybundle.vcxproj]
  dense.vcxproj -> D:\code\OpenSfM\cmake_build\dense\Release\dense.lib
  pydense.vcxproj -> D:\code\OpenSfM\opensfm\pydense.cp38-win_amd64.pyd
  akaze.vcxproj -> D:\code\OpenSfM\cmake_build\third_party\akaze\Release\akaze.lib
  vl.vcxproj -> D:\code\OpenSfM\cmake_build\third_party\vlfeat\Release\vl.lib
  features.vcxproj -> D:\code\OpenSfM\cmake_build\features\Release\features.lib
  pyfeatures.vcxproj -> D:\code\OpenSfM\opensfm\pyfeatures.cp38-win_amd64.pyd
  geo.vcxproj -> D:\code\OpenSfM\cmake_build\geo\Release\geo.lib
  pygeo.vcxproj -> D:\code\OpenSfM\opensfm\pygeo.cp38-win_amd64.pyd
  pybind.cc
D:/code/OpenSfM/vcpkg/installed/x64-windows/include\glog/log_severity.h(57,1): fatal error C1189: #error:  ERROR macro
is defined. Define GLOG_NO_ABBREVIATED_SEVERITIES before including logging.h. See the document for detail. [D:\code\Ope
nSfM\cmake_build\geometry\pygeometry.vcxproj]
  map.vcxproj -> D:\code\OpenSfM\cmake_build\map\Release\map.lib
  pymap.vcxproj -> D:\code\OpenSfM\opensfm\pymap.cp38-win_amd64.pyd
  relative_pose_model.cc
D:/code/OpenSfM/vcpkg/installed/x64-windows/include\glog/log_severity.h(57,1): fatal error C1189: #error:  ERROR macro
is defined. Define GLOG_NO_ABBREVIATED_SEVERITIES before including logging.h. See the document for detail. [D:\code\Ope
nSfM\cmake_build\robust\robust.vcxproj]
  instanciations.cc
D:/code/OpenSfM/vcpkg/installed/x64-windows/include\glog/log_severity.h(57,1): fatal error C1189: #error:  ERROR macro
is defined. Define GLOG_NO_ABBREVIATED_SEVERITIES before including logging.h. See the document for detail. [D:\code\Ope
nSfM\cmake_build\robust\robust.vcxproj]
  正在生成代码...
  ba_helpers.cc
D:/code/OpenSfM/vcpkg/installed/x64-windows/include\glog/log_severity.h(57,1): fatal error C1189: #error:  ERROR macro
is defined. Define GLOG_NO_ABBREVIATED_SEVERITIES before including logging.h. See the document for detail. [D:\code\Ope
nSfM\cmake_build\sfm\sfm.vcxproj]
Traceback (most recent call last):
  File "setup.py", line 60, in <module>
    build_c_extension()
  File "setup.py", line 50, in build_c_extension
    subprocess.check_call(
  File "C:\Users\24587\.conda\envs\uav\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release']' returned non-zero exit status 1.

**Comment by DodgySpaniard** [comment]
Apologies for the delay; this project was not monitored until recently.

We had many changes, and now we are moving to a better build/deploy system. Hopefully, this fixes the issue.

https://community.opendronemap.org/t/moving-the-odm-build-system-to-pixi/26795/6
